# Admin
USER_ID   : ''
PASSWORD  : ''

# Amazon S3
AMAZON_BUCKET_NAME: ''
AMAZON_KEY_ID: ''
AMAZON_ACCESS_KEY: ''


OFFICE_NAME : ''
LOGO_URL : ''

# Social media
FACEBOOK_LINK : ''
PINTEREST_LINK : ''
INSTAGRAM_LINK : ''
TWITTER_LINK : ''
GOOGLE_PLUS_LINK : ''
VIMEO_LINK : ''



