# Admin
USER_ID   : 'lam'
PASSWORD  : 'lam2013'

# Amazon S3
AMAZON_BUCKET_NAME: 'lam-site'
AMAZON_KEY_ID: 'AKIAJ5B54KTS37ZQW5SA'
AMAZON_ACCESS_KEY: '7WvPHGx8FEBzrw2Iw1tvn2dxBl7mVfKfcqQNu9E7'



OFFICE_NAME : 'studioLAM'
LOGO_URL : 'logo_studio_lam.jpg'

# Social media
FACEBOOK_LINK : ''
PINTEREST_LINK : ''
INSTAGRAM_LINK : ''
TWITTER_LINK : ''
GOOGLE_PLUS_LINK : ''
VIMEO_LINK : ''



